[package]
name = "javascript_grammar"
version = "0.1.0"
authors = ["Kevin Stenerson <developer@stenerson.me>"]
edition = "2018"

[dependencies]
grammar_utils = { path = "../../utils/grammar" }
test_utils = { path = "../../utils/test" }
combine = "3.8.1"
