// This file is automatically generated by running `cargo run -p antlr_codegen`.
//
// =====================
// Do not edit manually.
// =====================
//
#![allow(dead_code)]
#![allow(unused_imports)]

//! This module contains an auto-generated VUE parser.
use crate::syntax_kind::*;
use grammar_utils::{catch, tokenset, Parser, TokenSet};
use grammar_utils::parser::Continue;

pub fn component(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({
        while p.at_ts(&tokenset![COMMENT, L_ANGLE, WS]) {
            root_misc(p)?;
        }
        component_pattern(p)?;
        while p.at_ts(&tokenset![COMMENT, L_ANGLE, WS]) {
            root_misc(p)?;
        }
        Some(Continue)
    });
    p.complete(_marker, COMPONENT);
    _ok
}

pub fn component_pattern(p: &mut Parser) -> Option<Continue> {
    if p.at(L_ANGLE) && {
        // try --> script_block (root_misc)* template_block
        let mut _checkpoint = p.checkpoint(true);
        catch!({
            script_block(p)?;
            while p.at_ts(&tokenset![COMMENT, L_ANGLE, WS]) {
                root_misc(p)?;
            }
            template_block(p)?;
            Some(Continue)
        });
        p.commit(_checkpoint)?.is_ok()
    } {
        // ok
    } else if p.at(L_ANGLE) {
        template_block(p)?;
        while p.at_ts(&tokenset![COMMENT, L_ANGLE, WS]) {
            root_misc(p)?;
        }
        script_block(p)?;
    } else {
        // otherwise, emit an error
        p.expected(L_ANGLE)?;
    }
    Some(Continue)
}

pub fn template_block(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({ template_element(p) });
    p.complete(_marker, COMPONENT_TEMPLATE);
    _ok
}

pub fn template_element(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({
        p.expect(L_ANGLE)?;
        template_tag(p)?;
        p.eat(WS);
        while p.at_ts(&tokenset![AT, COLON, TAG_NAME]) {
            attribute(p)?;
            p.eat(WS);
        }
        p.expect(R_ANGLE)?;
        html_content(p)?;
        if p.at(L_ANGLE) {
            p.bump();
            p.expect(SLASH)?;
        } else if p.at(L_ANGLE_SLASH) {
            p.bump();
        } else {
            p.expected_ts(&tokenset![L_ANGLE, L_ANGLE_SLASH])?;
        }
        p.eat(WS);
        template_tag(p)?;
        p.eat(WS);
        p.expect(R_ANGLE)?;
        Some(Continue)
    });
    p.complete(_marker, ELEMENT);
    _ok
}

pub fn template_tag(p: &mut Parser) -> Option<Continue> {
    if !(p.at_keyword("template")) {
        p.error("expected input to be at keyword 'template'")?;
    }
    p.expect(TAG_NAME)?;
    Some(Continue)
}

pub fn script_block(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({ script_element(p) });
    p.complete(_marker, COMPONENT_SCRIPT);
    _ok
}

pub fn script_element(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({
        p.expect(L_ANGLE)?;
        script_tag(p)?;
        p.eat(WS);
        while p.at_ts(&tokenset![AT, COLON, TAG_NAME]) {
            attribute(p)?;
            p.eat(WS);
        }
        p.expect(R_ANGLE)?;
        script(p)?;
        if p.at(L_ANGLE) {
            p.bump();
            p.expect(SLASH)?;
        } else if p.at(L_ANGLE_SLASH) {
            p.bump();
        } else {
            p.expected_ts(&tokenset![L_ANGLE, L_ANGLE_SLASH])?;
        }
        p.eat(WS);
        script_tag(p)?;
        p.eat(WS);
        p.expect(R_ANGLE)?;
        Some(Continue)
    });
    p.complete(_marker, ELEMENT);
    _ok
}

pub fn script_tag(p: &mut Parser) -> Option<Continue> {
    if !(p.at_keyword("script")) {
        p.error("expected input to be at keyword 'script'")?;
    }
    p.expect(TAG_NAME)?;
    Some(Continue)
}

pub fn style_block(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({ style_element(p) });
    p.complete(_marker, COMPONENT_STYLE);
    _ok
}

pub fn style_element(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({
        p.expect(L_ANGLE)?;
        style_tag(p)?;
        p.eat(WS);
        while p.at_ts(&tokenset![AT, COLON, TAG_NAME]) {
            attribute(p)?;
            p.eat(WS);
        }
        p.expect(R_ANGLE)?;
        script(p)?;
        if p.at(L_ANGLE) {
            p.bump();
            p.expect(SLASH)?;
        } else if p.at(L_ANGLE_SLASH) {
            p.bump();
        } else {
            p.expected_ts(&tokenset![L_ANGLE, L_ANGLE_SLASH])?;
        }
        p.eat(WS);
        style_tag(p)?;
        p.eat(WS);
        p.expect(R_ANGLE)?;
        Some(Continue)
    });
    p.complete(_marker, ELEMENT);
    _ok
}

pub fn style_tag(p: &mut Parser) -> Option<Continue> {
    if !(p.at_keyword("style")) {
        p.error("expected input to be at keyword 'style'")?;
    }
    p.expect(TAG_NAME)?;
    Some(Continue)
}

pub fn root_misc(p: &mut Parser) -> Option<Continue> {
    if p.at(L_ANGLE) {
        style_block(p)?;
    } else if p.at(COMMENT) {
        p.bump();
    } else if p.at(WS) {
        p.bump();
    } else {
        p.expected_ts(&tokenset![COMMENT, L_ANGLE, WS])?;
    }
    Some(Continue)
}

pub fn attribute(p: &mut Parser) -> Option<Continue> {
    if (p.at(COLON) || (p.at_keyword("v-bind") && p.at(TAG_NAME))) && {
        // try --> ({ <predicate> }? TAG_NAME)? : attribute_key (attribute_modifier)* (WS)? = (WS)? attribute_value #ATTRIBUTE_BINDING
        let mut _checkpoint = p.checkpoint(true);
        catch!({
            let _marker = p.start();
            let _ok = catch!({
                if p.at_keyword("v-bind") && p.at(TAG_NAME) {
                    p.bump();
                }
                p.expect(COLON)?;
                attribute_key(p)?;
                while p.at(DOT) {
                    attribute_modifier(p)?;
                }
                p.eat(WS);
                p.expect(EQ)?;
                p.eat(WS);
                attribute_value(p)?;
                Some(Continue)
            });
            p.complete(_marker, ATTRIBUTE_BINDING);
            if _ok.is_none() {
                return None;
            }
            Some(Continue)
        });
        p.commit(_checkpoint)?.is_ok()
    } {
        // ok
    } else if (p.at(AT) || (p.at_keyword("v-on") && p.at(TAG_NAME))) && {
        // try --> ({ <predicate> }? TAG_NAME | @) attribute_key (attribute_modifier)* (WS)? = (WS)? attribute_value #ATTRIBUTE_LISTENER
        let mut _checkpoint = p.checkpoint(true);
        catch!({
            let _marker = p.start();
            let _ok = catch!({
                if p.at_keyword("v-on") && p.at(TAG_NAME) {
                    p.bump();
                } else if p.at(AT) {
                    p.bump();
                }
                attribute_key(p)?;
                while p.at(DOT) {
                    attribute_modifier(p)?;
                }
                p.eat(WS);
                p.expect(EQ)?;
                p.eat(WS);
                attribute_value(p)?;
                Some(Continue)
            });
            p.complete(_marker, ATTRIBUTE_LISTENER);
            if _ok.is_none() {
                return None;
            }
            Some(Continue)
        });
        p.commit(_checkpoint)?.is_ok()
    } {
        // ok
    } else if p.at(TAG_NAME) && {
        // try --> TAG_NAME (WS)? = (WS)? attribute_value #ATTRIBUTE
        let mut _checkpoint = p.checkpoint(true);
        catch!({
            let _marker = p.start();
            let _ok = catch!({
                p.bump();
                p.eat(WS);
                p.expect(EQ)?;
                p.eat(WS);
                attribute_value(p)?;
                Some(Continue)
            });
            p.complete(_marker, ATTRIBUTE);
            if _ok.is_none() {
                return None;
            }
            Some(Continue)
        });
        p.commit(_checkpoint)?.is_ok()
    } {
        // ok
    } else if p.at(TAG_NAME) {
        let _marker = p.start();
        p.bump();
        p.complete(_marker, ATTRIBUTE);
    } else {
        // otherwise, emit an error
        p.expected_ts(&tokenset![AT, COLON, TAG_NAME])?;
    }
    Some(Continue)
}

pub fn attribute_modifier(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({
        p.expect(DOT)?;
        p.expect(TAG_NAME)?;
        Some(Continue)
    });
    p.complete(_marker, ATTRIBUTE_MODIFIER);
    _ok
}

pub fn attribute_key(p: &mut Parser) -> Option<Continue> {
    if p.at(L_SQUARE) {
        let _marker = p.start();
        let _ok = catch!({
            p.bump();
            p.eat(WS);
            p.expect(TAG_NAME)?;
            p.eat(WS);
            p.expect(R_SQUARE)?;
            Some(Continue)
        });
        p.complete(_marker, ATTRIBUTE_KEY);
        if _ok.is_none() {
            return None;
        }
    } else if p.at(TAG_NAME) {
        let _marker = p.start();
        p.bump();
        p.complete(_marker, ATTRIBUTE_KEY);
    } else {
        p.expected_ts(&tokenset![L_SQUARE, TAG_NAME])?;
    }
    Some(Continue)
}

pub fn element(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({ element_pattern(p) });
    p.complete(_marker, ELEMENT);
    _ok
}

pub fn element_pattern(p: &mut Parser) -> Option<Continue> {
    p.expect(L_ANGLE)?;
    if ((p.at_keyword("area") || p.at_keyword("base") || p.at_keyword("br") || p.at_keyword("col") || p.at_keyword("embed") || p.at_keyword("hr") || p.at_keyword("img") || p.at_keyword("input") || p.at_keyword("link") || p.at_keyword("meta") || p.at_keyword("param") || p.at_keyword("source") || p.at_keyword("track") || p.at_keyword("wbr")) && p.at(TAG_NAME)) && {
        // try --> empty_element_tag_name (WS)? (attribute (WS)?)* (> | />)
        let mut _checkpoint = p.checkpoint(true);
        catch!({
            empty_element_tag_name(p)?;
            p.eat(WS);
            while p.at_ts(&tokenset![AT, COLON, TAG_NAME]) {
                attribute(p)?;
                p.eat(WS);
            }
            p.expect_ts(&tokenset![R_ANGLE, SLASH_R_ANGLE])?;
            Some(Continue)
        });
        p.commit(_checkpoint)?.is_ok()
    } {
        // ok
    } else if p.at(TAG_NAME) {
        p.bump();
        p.eat(WS);
        while p.at_ts(&tokenset![AT, COLON, TAG_NAME]) {
            attribute(p)?;
            p.eat(WS);
        }
        if p.at(SLASH_R_ANGLE) {
            p.bump();
        } else if p.at(R_ANGLE) {
            p.bump();
            html_content(p)?;
            if p.at(L_ANGLE) {
                p.bump();
                p.expect(SLASH)?;
            } else if p.at(L_ANGLE_SLASH) {
                p.bump();
            } else {
                p.expected_ts(&tokenset![L_ANGLE, L_ANGLE_SLASH])?;
            }
            p.eat(WS);
            p.expect(TAG_NAME)?;
            p.eat(WS);
            p.expect(R_ANGLE)?;
        } else {
            p.expected_ts(&tokenset![R_ANGLE, SLASH_R_ANGLE])?;
        }
    } else {
        // otherwise, emit an error
        p.expected(TAG_NAME)?;
    }
    Some(Continue)
}

pub fn empty_element_tag_name(p: &mut Parser) -> Option<Continue> {
    if p.at_keyword("area") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("base") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("br") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("col") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("embed") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("hr") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("img") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("input") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("link") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("meta") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("param") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("source") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("track") && p.at(TAG_NAME) {
        p.bump();
    } else if p.at_keyword("wbr") && p.at(TAG_NAME) {
        p.bump();
    } else {
        // otherwise, emit an error
        p.expected(TAG_NAME)?;
    }
    Some(Continue)
}

pub fn attribute_value(p: &mut Parser) -> Option<Continue> {
    p.expect_ts(&tokenset![QUOTED, TAG_NAME])
}

pub fn html_content(p: &mut Parser) -> Option<Continue> {
    if p.at_ts(&tokenset![COMMENT, L_ANGLE, TEXT, WHITESPACE]) {
        if p.at_ts(&tokenset![TEXT, WHITESPACE]) {
            html_chardata(p)?;
        }
        while p.at_ts(&tokenset![COMMENT, L_ANGLE]) {
            if p.at(L_ANGLE) {
                element(p)?;
            } else if p.at(COMMENT) {
                p.bump();
            }
            if p.at_ts(&tokenset![TEXT, WHITESPACE]) {
                html_chardata(p)?;
            }
        }
    } else if p.at(SCRIPT_CONTENT) {
        if p.at(SCRIPT_CONTENT) {
            script(p)?;
        }
    }
    Some(Continue)
}

pub fn html_chardata(p: &mut Parser) -> Option<Continue> {
    p.expect_ts(&tokenset![TEXT, WHITESPACE])
}

pub fn script(p: &mut Parser) -> Option<Continue> {
    let _marker = p.start();
    let _ok = catch!({ p.expect(SCRIPT_CONTENT) });
    p.complete(_marker, SCRIPT);
    _ok
}
