[workspace]
members = [
  "analysis/vue",
  "codegen/antlr",
  "codegen/estree",
  "lang/javascript",
  "lang/typescript",
  "lang/html",
  "lang/vue",
  "utils/analysis",
  "utils/grammar",
  "utils/test",
]
