[workspace]
members = [
  "analysis/vue",
  "codegen/antlr",
  "codegen/estree",
  "grammar/javascript",
  "grammar/typescript",
  "grammar/html",
  "grammar/vue",
  "utils/analysis",
  "utils/grammar",
  "utils/test",
]
