[package]
name = "typescript_grammar"
version = "0.1.0"
authors = ["Kevin Stenerson <developer@stenerson.me>"]
edition = "2018"

[dependencies]
code_grammar = { path = "../../utils/grammar" }
javascript_grammar = { path = "../javascript" }