[package]
name = "estree_grammar"
version = "0.1.0"
authors = ["Kevin Stenerson <developer@stenerson.me>"]
edition = "2018"

[dependencies]
combine = "3.8.1"
web_grammars_utils = { path = "../../utils" }
heck = "0.3.1"
