[package]
name = "antlr_codegen"
version = "0.1.0"
authors = ["Kevin Stenerson <developer@stenerson.me>"]
edition = "2018"

[[bin]]
name = "antlr_generate"
path = "src/bin/generate.rs"

[dependencies]
combine = "3.8.1"
heck = "0.3.1"
smol_str = "0.1.10"
petgraph = "0.4.13"
