[package]
name = "vue_analyzer"
version = "0.1.0"
authors = ["Kevin Stenerson <kstenerson@developers.wyyerd.com>"]
edition = "2018"

[dependencies]
html_grammar = { path = "../../lang/html" }
javascript_grammar = { path = "../../lang/javascript" }
web_analysis_utils = { path = "../../utils/analysis" }
web_grammar_utils = { path = "../../utils/grammar" }
salsa = "0.12.0"

[dev-dependencies]
difference = "2.0.0"
