[package]
name = "vue_analyzer"
version = "0.1.0"
authors = ["Kevin Stenerson <kstenerson@developers.wyyerd.com>"]
edition = "2018"

[dependencies]
salsa = "0.12.0"

analysis_utils = { path = "../../utils/analysis" }
grammar_utils = { path = "../../utils/grammar" }
html_grammar = { path = "../../lang/html" }
javascript_grammar = { path = "../../lang/javascript" }

[dev-dependencies]
test_utils = { path = "../../utils/test" }
